server:
  port: 8081



spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.240.108:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890qpQP@

  redis:
    host: 47.107.240.108
    port: 6379
    database: 3  # 注意：是 database 不是 db-index
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        time-between-eviction-runs: 3000ms

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段


mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug